/// Flutter icons Balloons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Balloons
///      fonts:
///       - asset: fonts/Balloons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Balloons {
  Balloons._();

  static const _kFontFam = 'Balloons';
  static const _kFontPkg = null;

  static const IconData balloons_removebg_preview = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
